apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: terraform-101
spec:
  vendor: terasky
  duration: 45m
  difficulty: beginner
  content:
    files: github.com/vrabbi/learning-center-terraform-101?ref=main
  description: intro to terraform
  session:
    resources:
      memory: 1Gi
    applications:
      console:
        enabled: true
        vendor: kubernetes
      docker:
        enabled: false
      editor:
        enabled: true
      registry:
        enabled: false
      terminal:
        enabled: true
        layout: split/2
    namespaces:
      budget: small
  title: Terraform 101 Course
